name: Run Tests

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: test-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    services:
      rabbit:
        image: rabbitmq:management-alpine
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672:5672
          - 15672:15672
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Node.js LTS
        uses: actions/setup-node@v4.2.0
        with:
          node-version: lts/*
          registry-url: "https://npm.pkg.github.com"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npm test
        env:
          AMQP_ADDRESS: rabbit

      - name: Check linting
        run: npm run lint
